### ISSUE TITLE
SetViewportToSizeOf class equality should be dependent on width/height, not fbo name

### ISSUE THREAD

**Issue by emanuele3d** [MovingBlocks/Terasology#2688]
### What you were trying to do
Ensure glViewport is called only if necessary.

### What actually happened
It gets called whenever the FBO changes from one node to the next. Should change only when the width/height dimensions of the FBOs in consecutive nodes change.

### How to reproduce
- Run Terasology, start a game, exit terasology.
- Check log for RENDER TASK LIST: consecutive nodes should have SetViewportToSizeOfTask lines with different width/height values, or the following nodes should have no SetViewportToSizeOfTask line at all.

### Cause
This is due to the SetViewportToSizeOf class comparing instances based on the name of the FBO they get the dimensions from. Instead, they should compare the width and height values. Methods hashCode and equals must be refactored accordingly. Obtaining the fbo dimensions is the architectural challenge.

It shouldn't be too difficult but must be handled carefully.

**Comment by eviltak** [comment]
@emanuele3d @rzats I'd like to claim this issue as part of GCI.

**Comment by rzats** [comment]
@eviltak: added this to the tracker 🙂 https://codein.withgoogle.com/tasks/6572021636923392/

**Comment by eviltak** [comment]
@rzats thank you. @emanuele3d This change does not bring about any improvements, since persistent changes of type `SetViewportToSizeOf` are removed and the (sometimes redundant if moving to the same size, the point addressed by this issue) reset task added if the next node does not contain a `SetViewportToSizeOf` state change. This can be addressed by doing a value equality check inside `RenderTaskListGenerator.sameClassStateChangeNotFoundInThe()`. The note in the said method says that an equality check is not required as it will be processed by the next node, but it does lead to creation of a sometimes redundant reset task. 

For instance, look at the tasks generated for `ApplyDeferredLightingNode`.

```
18:51:13.518 [main] INFO  o.t.r.dag.RenderTaskListGenerator -        SetViewportToSizeOfTask: engine:sceneOpaquePingPong (1152x720)
18:51:13.518 [main] INFO  o.t.r.dag.RenderTaskListGenerator -             EnableMaterialTask: engine:prog.lightBufferPass
18:51:13.518 [main] INFO  o.t.r.dag.RenderTaskListGenerator -            SetInputTextureTask: slot 0, texture 145, material engine:prog.lightBufferPass, parameter texSceneOpaque
18:51:13.518 [main] INFO  o.t.r.dag.RenderTaskListGenerator -            SetInputTextureTask: slot 1, texture 148, material engine:prog.lightBufferPass, parameter texSceneOpaqueDepth
18:51:13.518 [main] INFO  o.t.r.dag.RenderTaskListGenerator -            SetInputTextureTask: slot 2, texture 146, material engine:prog.lightBufferPass, parameter texSceneOpaqueNormals
18:51:13.518 [main] INFO  o.t.r.dag.RenderTaskListGenerator -            SetInputTextureTask: slot 3, texture 147, material engine:prog.lightBufferPass, parameter texSceneOpaqueLightBuffer
18:51:13.518 [main] INFO  o.t.r.dag.RenderTaskListGenerator -      ApplyDeferredLightingNode: process()
18:51:13.518 [main] INFO  o.t.r.dag.RenderTaskListGenerator -        SetViewportToSizeOfTask: engine:sceneOpaque (1152x720)
18:51:13.518 [main] INFO  o.t.r.dag.RenderTaskListGenerator -            SetInputTextureTask: slot 0, texture 0, material engine:prog.lightBufferPass, parameter texSceneOpaque
18:51:13.519 [main] INFO  o.t.r.dag.RenderTaskListGenerator -            SetInputTextureTask: slot 1, texture 0, material engine:prog.lightBufferPass, parameter texSceneOpaqueDepth
18:51:13.519 [main] INFO  o.t.r.dag.RenderTaskListGenerator -            SetInputTextureTask: slot 2, texture 0, material engine:prog.lightBufferPass, parameter texSceneOpaqueNormals
18:51:13.519 [main] INFO  o.t.r.dag.RenderTaskListGenerator -            SetInputTextureTask: slot 3, texture 0, material engine:prog.lightBufferPass, parameter texSceneOpaqueLightBuffer
```

I'll give you guys an update after modifying the method to do the equality check too.

**Comment by emanuele3d** [comment]
@eviltak, thank you for taking this task onboard and thanks @rzats for taking care of the GCI-side logistics.

@eviltak: I need you to spend some more time on working on your grammar as what you wrote is not very clear.

From what I understand you want to add an equality check in RenderTaskListGenerator.sameClassStateChangeNotFoundInThe(). 

It is unclear to me why you think there is a deficiency in that method. In the log snippet you quote I can only see a problem with the SetViewportToSizeOfTask, which is exactly the point of this issue: if SetViewportToSizeOf state changes were compared on the basis of dimensions instead of FBO name the second state change would not occur. This is addressed in the SetViewportToSizeOf class, where the equality check is based.

That been said, I just noticed that the original description I wrote for this issue has a mistake. It says:
_"This is due to the SetViewportToSizeOfTask class comparing instances...."_ This is incorrect as the equality check is done in the state change, not the task. So SetViewportToSizeOf is the class to modify, as that's where the equality check exists and needs to be improved. 

I will now proceed to correct the mistake. Let me know if you need further clarifications.

**Comment by eviltak** [comment]
@emanuele3d I'm sorry, I wrote that in a hurry and made some slightly incorrect assumptions. The explanation of the problem follows. I will open a PR soon after writing this.

Using dimensions instead of the FBO name while comparing instances of `SetViewportSizeOf` is just _part_ of the problem, which eviltak@a12bab3 addresses. Simply changing the instance comparison method does not solve the problem. Try it out, it will make absolutely no difference to the number of tasks generated.

The second part of the problem lies in the second half of the method `RenderTaskListGenerator.generateFrom()`, which checks whether state change reset tasks need to be added to the list. The current code first 

1. Checks whether the next node contains a state change of the same _type_ as the state change reset, no equality check is performed. 
2. If it doesn't, it goes ahead and 
  a. Adds the state change reset task to the task list and 
  b. _Removes_ the already **persisting** state change of the same type (this is the important bit).

This leads to the following problems: 
- Since no equality check is performed, the state change reset _may_ be redundant. For example, the state change reset will still be added even when the `SetViewportSizeOf` state change has the same dimensions as the state change reset, even if eviltak@a12bab3 is implemented.
- Since the already persisting state change is removed, there is no way for future state changes to know if they are identical to the previously performed state change and hence redundant, even if eviltak@a12bab3 is implemented.

Therefore, the state change resets section of `generateFrom()` needs to be modified to include
- An equality check with already persisting state changes
- Marking of the state change reset as persistent _if_ it is deemed necessary and added to the task list.

The second part of the problem is not specific to `SetViewportSizeOf`, it is for all state changes. So this holds true for _all_ future `StateChange`s whose instances can be value-identical.

**Comment by emanuele3d** [comment]
@eviltak, thank you for your effort.

Let me quote what you write:

> - Since no equality check with the persisting state is performed, the state change reset may be redundant. For example, the state change reset will still be added even when the persisting SetViewportSizeOf state change has the same dimensions as the state change reset, even if eviltak@a12bab3 is implemented.

Generally speaking a state change reset will bring an opengl parameter back to its opengl default or back to Terasology's default. This way the next node doesn't have to add a new desired state change unless it wants a non-default value. So, the code assumes (but does not enforce) that a desired state change sets the parameter to non-default value. In this context an equality check with the reset state change is unnecessary because if there is a persistent state change in the map it is supposed to be setting a non-default value. We can certainly discuss what we can do to enforce non-default values for a desired state change, but it would be a separate issue and I'm grateful you pointed it out.

> - Since the already persisting state change is removed, there is no way for future state changes to know if they are identical to the previously performed (persisted) state change and hence redundant, even if eviltak@a12bab3 is implemented.

The persistent state change of a given type is removed only if the next node does not require a state change of the same type. This implies the next node requires opengl's or terasology's default value for that parameter. Let me make an example:

- Node A desires FaceCulling: a task enables it, but as the next node requires it too, no reset task is added to the tasklist and the state change gets into the persistentStateChanges map.
- Nodes B desires FaceCulling: as FaceCulling is already enabled by the previous node this node does not add a new enabling task to the tasklist about it. However, as the next node does not require it, this node adds a reset task so that FaceCulling is disabled, as per OpenGL default. Furthermore, it removes the FaceCulling state change from the persistent map. 
Nodes C does not need FaceCulling: the previous node added the reset task to disable it, so this node has nothing to do on the matter.
Node D desires FaceCulling again: this node finds FaceCulling disabled, as per opengl default, and causes a task to enable it again. It briefly adds the state change to the persistent map, but as it is the last node of the list it removes it right away and adds a reset task, so that other parts of Terasology (i.e. the UI) find the opengl default.

In this context I'm not finding anything unwanted in the TaskListGenerator code: as far as I can see from the difference between the Intermediate Renderer List and the Renderer Task List (in the log) redundant state changes are correctly eliminated with one exception: the SetViewportToSizeOf state changes. 

I wonder if the "persistentStateChanges" map is confusing. That map contains a state change only as long as _a consecutive group of nodes requires it_. If two groups of nodes are separated by one or more nodes that do not require it, the state change will be removed from that map and then added again to it when the second group of nodes is iterated over. This is the intended behavior. 

I'm thinking there might be a misunderstanding that needs to be clarified in the TaskListGenerator code or in the associated documentation.

**Comment by eviltak** [comment]
Note that the addition to the code does not remove the intended behaviour, it merely extends it. That is,
> If two groups of nodes are separated by one or more nodes that do not require it, the state change will be removed from that map and then added again to it when the second group of nodes is iterated over 

is still what would happen.

I'll take an example using `SetViewportToSizeOf` (only considering the dimensions and not the FBO name since it doesn't make a difference) state changes to explain where the existing behavior misses out.

Consider the following nodes with the following state changes:
```
--- FirstNode
    SetViewportToSizeOf: 640x480
--- SecondNode
    SetViewportToSizeOf: 1024x1024
--- RandomNode1
    SomeRandomStateChange
--- ThirdNode
    SetViewportToSizeOf: 1920x1080
--- RandomNode2
    SomeRandomStateChange
--- FourthNode
     SetViewportToSizeOf: 1920x1080
```

The existing code will produce the following tasks (1920x1080 is the default `SetViewportToSizeOf` state change):
```
--- FirstNode
    SetViewportToSizeOfTask: 640x480
    FirstNode.process()
--- SecondNode
    SetViewportToSizeOfTask: 1024x1024
    SecondNode.process()
    SetViewportToSizeOfTask: 1920x1080 (reset)
--- RandomNode1
    SomeRandomStateChange
    RandomNode1.process()
    SomeRandomStateChange (reset)
--- ThirdNode
    *1 SetViewportToSizeOfTask: 1920x1080
    ThirdNode.process()
    *2 SetViewportToSizeOfTask: 1920x1080 (reset)
--- RandomNode2
    SomeRandomStateChange
    RandomNode2.process()
    SomeRandomStateChange (reset)
--- FourthNode
     *3 SetViewportToSizeOfTask: 1920x1080
    FourthNode.process()
    *4 SetViewportToSizeOfTask: 1920x1080 (reset)
```

I have put an asterisk along with a number label before all the redundant tasks. 

Now, as we implement the first of the two proposed features in the state change resets section of `generateFrom()`, i.e. "an equality check with already persisting state changes", we will be able to remove *2 and *4 since they are identical to the previous `SetViewportToSizeOf` state changes performed. With the removal of *2, *1 will not be deleted from the persisted state changes (since no reset is performed), therefore *3 can also be removed. So in total, *2, *3 and *4 are removed. Note that we haven't yet implemented the second feature in our hypothetical example.

On implementing the second feature, i.e. "marking the state change reset as persistent instead of deleting the persisted state change if the reset is deemed necessary and is added to the task list", *1 can also be removed. Since, instead of removing the persisted state change, the state change reset in SecondNode is persisted, *1 is deleted as it is identical to the persisted state change (i.e. the state change reset in SecondNode). 

To address some of your reservations:

> as far as I can see from the difference between the Intermediate Renderer List and the Renderer Task List (in the log) redundant state changes are correctly eliminated with one exception: the SetViewportToSizeOf state changes.

This is because `SetViewportToSizeOf` is the _only_ `StateChange` whose instances have a possibility of being value equal. No other `StateChange` has _any_ two instances which are **value equal** (not considering the state resets). Furthermore,  no other `StateChange` has non-reset instances which are value identical to the reset instances _with or without_ a node which does not contain a `StateChange` of the same type in between them.

**Comment by emanuele3d** [comment]
@eviltak: thank you for your analyses and for the example you make, it certainly makes your thinking very clear. 

On the first issue. I agree that in your example state changes 1 to 4 are redundant given that they all match the default. However, the error is not in the reset state changes but in using instances of SetViewportToSizeOf that set the viewport to default values. Those nodes should not have a SetViewportToSizeOf instance among their desired state changes. This is the cause of those redundant state changes and this what needs to be addressed: desired state changes should only be allowed to have non-default values. By focusing on the reset you are focusing on the symptoms, not the cause. I want to get the cause addressed and it deserves a separate issue.

On the second issue:

> This is because SetViewportToSizeOf is the only StateChange whose instances have a possibility of being value equal. No other StateChange has any two instances which are value equal (not considering the state resets).

Perhaps I'm not understanding what you mean here. Many, if not all, state changes have a possibility of being value equal. Take for example the BindFBO state change. Nodes BufferClearingNode, BackdropReflectionNode, WorldReflectionNode all use it to request binding to the same non-default FBO: sceneReflected. The TaskListGenerator correctly adds a BindFBOTask when iterating over the first node, but does not for the next two because it found the desired state changes to be value-equal to the persistent one. So, I'm not sure what you mean here?

> Furthermore, no other StateChange has non-reset instances which are value identical to the reset instances with or without a node which does not contain a StateChange of the same type in between them.

As I mentioned above this isn't meant to happen. If you are a module developer and you make a new node you should know that it doesn't make sense to add a SetViewportToSizeOf state change with dimensions that are the same as the gbuffer, as that should be [1] the default. Right now I'm still in a mopping-up phase after the GSOC. I feel that these issues with FBOs and viewports will be slowly addressed by my cleanup. But ultimately non-reset StateChange instances should always have non-default values. And that's what we need to address.

[1] Thanks to this discussion I realized that the dimensions of the gbuffer are not the default: the dimensions of the display are. In  normal circumstances this is not a problem but when taking a screenshot the display dimensions can be different from the dimensions of the gbuffer. Another issue to address.

**Comment by eviltak** [comment]
@emanuele3d I now understand the real problem, and the scope of this issue. The primary cause of duplicate `SetViewportToSizeOf` state changes is that these duplicates are a duplicate of the default state change, and state changes value identical to the default state change should preferably _not_ be added to the desired state changes list.

As such, the scope of this issue and the related PR #2702 is limited to eviltak@a12bab3. I will revert the changes to `RenderTaskListGenerator` in a new commit to the PR branch (I prefer this to deleting commits) and create a new issue for the above problem.

**Comment by eviltak** [comment]
The crux of the problem is the `isDefaultInstance` method, which does a _reference_ comparison instead of a value comparison. This problem is (or will be) apparent in all `StateChange`s that can be value identical (i.e. implement a custom `equals` method) and have a default state. As this is out of scope of this issue and #2702, #2702 can be merged for now as it fulfills its purpose, and value equality in the `isDefaultInstance` methods of _all_ `StateChange`s will be implemented in a future PR.
