### ISSUE TITLE
Torches give only light underwater on lower graphic settings

### ISSUE THREAD

**Issue by flo** [MovingBlocks/Terasology#2943]
### What you were trying to do
Diving in a cave while holding a torch

### What actually happened
Depending on graphic settings I got different results:
- Medium: Almost completely dark
- Low: Acceptable good lighting as long as you don't go to close to a wall. In that case the light radius will shrink until everything is dark.

### How to reproduce

* Dive while holding  a torch. Ideally underground but even overground it is quite dark

### Log details and game version
I used the current development branch: 606796b540d43f9baae9a9e130811a9d748c7e8e

**Comment by cheekujodhpur** [comment]
Hey, I could not reproduce this. 

This is an old issue. Maybe something else fixed this. Could someone else check as well?

**Comment by emanuele3d** [comment]
@flo: I also can't reproduce this. A number of changes have occurred in the renderer and the problem might have been solved. Is it ok if we close this issue?

That been said, the underwater rendering remains unacceptable though, as it no longer has a tint nor any blur effects. I have opened issue #3052 to work on the look from above the water and I plan to open another issue specifically for the underwater look.

**Comment by cheekujodhpur** [comment]
Yes. I recently cloned this repo and was indeed having a desire  to work on that issue. 
But it is a large codebase so maybe I should do something small first. @nihal111 invited me to discuss this with you on IRC. I'm looking forward to that soon

**Comment by emanuele3d** [comment]
@cheekujodhpur: I am online now if you want to have a quick chat.

**Comment by Cervator** [comment]
Agreed on closing this if it no longer occurs - on the other hand maybe it is for specific systems? @flo could you try and see if it still happens for you?

**Comment by flo** [comment]
I can still reproduce the issue with current trunk:

To test this I started a game with the GooeysQuest module and then cheated myself the toolbox item. Then I activated the item and used it to get a dungeonTownWell spawner. Then I used the ghost cheat to fly deep underground and spawned the dungeonTownWell structure by right clicking with the spawner. Then I floated into the water and threw a torch

It looked then like this for me:
![torchlightunderwaterbug](https://user-images.githubusercontent.com/3511/29287429-ab6feb54-8135-11e7-99a1-5f28f544951d.png)

In the screenshot you can see that the area around the torch isn't litup at all but a little farer away it lits up the wall a little bit.
